# -*- coding: utf-8 -*-
"""Terjemahan Korea untuk unit 5-16 (kunci = kata/kalimat Inggris di course_units_master.py).

Nilai = (target Hangul, Revised Romanization). Kata kerja/sifat dalam bentuk
kamus (-다), kata benda tanpa partikel. Semua target unik terhadap ko.json.
"""

WORDS = {
  # u5 More Numbers
  'six': ('여섯', 'yeoseot'),
  'seven': ('일곱', 'ilgop'),
  'eight': ('여덟', 'yeodeol'),
  'nine': ('아홉', 'ahop'),
  'hundred': ('백', 'baek'),
  'zero': ('영', 'yeong'),
  'twenty': ('이십', 'isip'),
  'thirty': ('삼십', 'samsip'),
  'fifty': ('오십', 'osip'),
  'thousand': ('천', 'cheon'),
  'million': ('백만', 'baengman'),
  'number': ('숫자', 'sutja'),
  'age': ('나이', 'nai'),
  'year': ('년', 'nyeon'),
  'first': ('첫 번째', 'cheot beonjjae'),
  'second': ('두 번째', 'du beonjjae'),
  'last': ('마지막', 'majimak'),
  'old': ('늙다', 'neukda'),

  # u6 Colors
  'red': ('빨간색', 'ppalgansaek'),
  'blue': ('파란색', 'paransaek'),
  'yellow': ('노란색', 'noransaek'),
  'green': ('초록색', 'choroksaek'),
  'black': ('검은색', 'geomeunsaek'),
  'white': ('흰색', 'huinsaek'),
  'orange': ('주황색', 'juhwangsaek'),
  'purple': ('보라색', 'borasaek'),
  'pink': ('분홍색', 'bunhongsaek'),
  'brown': ('갈색', 'galsaek'),
  'gray': ('회색', 'hoesaek'),
  'color': ('색깔', 'saekkkal'),
  'bright': ('밝다', 'bakda'),
  'dark': ('어둡다', 'eodupda'),
  'favorite': ('가장 좋아하는', 'gajang joahaneun'),
  'like': ('좋아하다', 'joahada'),
  'beautiful': ('아름답다', 'areumdapda'),
  'ugly': ('못생기다', 'motsaenggida'),

  # u7 Animals
  'cat': ('고양이', 'goyangi'),
  'dog': ('개', 'gae'),
  'bird': ('새', 'sae'),
  'rabbit': ('토끼', 'tokki'),
  'hamster': ('햄스터', 'haemseuteo'),
  'pet': ('반려동물', 'ballyeodongmul'),
  'elephant': ('코끼리', 'kokkiri'),
  'lion': ('사자', 'saja'),
  'tiger': ('호랑이', 'horangi'),
  'horse': ('말', 'mal'),
  'cow': ('소', 'so'),
  'monkey': ('원숭이', 'wonsungi'),
  'frog': ('개구리', 'gaeguri'),
  'turtle': ('거북이', 'geobugi'),
  'shark': ('상어', 'sangeo'),
  'butterfly': ('나비', 'nabi'),
  'ant': ('개미', 'gaemi'),
  'mosquito': ('모기', 'mogi'),

  # u8 Days & Weeks
  'Monday': ('월요일', 'woryoil'),
  'Tuesday': ('화요일', 'hwayoil'),
  'Wednesday': ('수요일', 'suyoil'),
  'Thursday': ('목요일', 'mogyoil'),
  'Friday': ('금요일', 'geumyoil'),
  'day': ('하루', 'haru'),
  'Saturday': ('토요일', 'toyoil'),
  'Sunday': ('일요일', 'iryoil'),
  'weekend': ('주말', 'jumal'),
  'week': ('주', 'ju'),
  'month': ('달', 'dal'),
  'holiday': ('휴일', 'hyuil'),
  'always': ('항상', 'hangsang'),
  'usually': ('보통', 'botong'),
  'sometimes': ('가끔', 'gakkeum'),
  'never': ('절대', 'jeoldae'),
  'every day': ('매일', 'maeil'),
  'often': ('자주', 'jaju'),

  # u9 Weather & Seasons
  'weather': ('날씨', 'nalssi'),
  'sunny': ('맑다', 'makda'),
  'cloudy': ('흐리다', 'heurida'),
  'windy': ('바람이 불다', 'barami bulda'),
  'rain': ('비', 'bi'),
  'snow': ('눈송이', 'nunsongi'),
  'season': ('계절', 'gyejeol'),
  'spring': ('봄', 'bom'),
  'summer': ('여름', 'yeoreum'),
  'autumn': ('가을', 'gaeul'),
  'winter': ('겨울', 'gyeoul'),
  'dry season': ('건기', 'geongi'),
  'hot': ('덥다', 'deopda'),
  'cold': ('춥다', 'chupda'),
  'warm': ('따뜻하다', 'ttatteuthada'),
  'cool': ('시원하다', 'siwonhada'),
  'temperature': ('온도', 'ondo'),
  'umbrella': ('우산', 'usan'),

  # u10 Body & Health
  'head': ('머리', 'meori'),
  'eye': ('눈', 'nun'),
  'ear': ('귀', 'gwi'),
  'nose': ('코', 'ko'),
  'mouth': ('입', 'ip'),
  'hair': ('머리카락', 'meorikarak'),
  'hand': ('손', 'son'),
  'finger': ('손가락', 'songarak'),
  'foot': ('발', 'bal'),
  'arm': ('팔', 'pal'),
  'stomach': ('배', 'bae'),
  'back': ('등', 'deung'),
  'sick': ('아프다', 'apeuda'),
  'healthy': ('건강하다', 'geonganghada'),
  'doctor': ('의사', 'uisa'),
  'medicine': ('약', 'yak'),
  'hospital': ('병원', 'byeongwon'),
  'pain': ('통증', 'tongjeung'),

  # u11 Clothing
  'shirt': ('셔츠', 'syeocheu'),
  'pants': ('바지', 'baji'),
  'dress': ('드레스', 'deureseu'),
  'skirt': ('치마', 'chima'),
  'jacket': ('재킷', 'jaekit'),
  'clothes': ('옷', 'ot'),
  'hat': ('모자', 'moja'),
  'shoes': ('신발', 'sinbal'),
  'socks': ('양말', 'yangmal'),
  'bag': ('가방', 'gabang'),
  'watch': ('손목시계', 'sonmoksigye'),
  'glasses': ('안경', 'angyeong'),
  'wear': ('입다', 'ipda'),
  'take off': ('벗다', 'beotda'),
  'size': ('사이즈', 'saijeu'),
  'new': ('새롭다', 'saeropda'),
  'clean': ('깨끗하다', 'kkaekkeuthada'),
  'dirty': ('더럽다', 'deoreopda'),

  # u12 School
  'book': ('책', 'chaek'),
  'pen': ('펜', 'pen'),
  'pencil': ('연필', 'yeonpil'),
  'paper': ('종이', 'jongi'),
  'eraser': ('지우개', 'jiugae'),
  'notebook': ('공책', 'gongchaek'),
  'school': ('학교', 'hakgyo'),
  'class': ('수업', 'sueop'),
  'classroom': ('교실', 'gyosil'),
  'homework': ('숙제', 'sukje'),
  'test': ('시험', 'siheom'),
  'question': ('질문', 'jilmun'),
  'learn': ('배우다', 'baeuda'),
  'understand': ('이해하다', 'ihaehada'),
  'remember': ('기억하다', 'gieokhada'),
  'forget': ('잊다', 'itda'),
  'answer': ('대답하다', 'daedaphada'),
  'ask': ('묻다', 'mutda'),

  # u13 Work & Jobs
  'job': ('직업', 'jigeop'),
  'nurse': ('간호사', 'ganhosa'),
  'police officer': ('경찰관', 'gyeongchalgwan'),
  'farmer': ('농부', 'nongbu'),
  'cook': ('요리사', 'yorisa'),
  'driver': ('운전사', 'unjeonsa'),
  'engineer': ('엔지니어', 'enjinieo'),
  'lawyer': ('변호사', 'byeonhosa'),
  'singer': ('가수', 'gasu'),
  'artist': ('예술가', 'yesulga'),
  'businessman': ('사업가', 'saeopga'),
  'pilot': ('조종사', 'jojongsa'),
  'office': ('사무실', 'samusil'),
  'meeting': ('회의', 'hoeui'),
  'computer': ('컴퓨터', 'keompyuteo'),
  'boss': ('상사', 'sangsa'),
  'salary': ('월급', 'wolgeup'),
  'busy': ('바쁘다', 'bappeuda'),

  # u14 Transportation
  'car': ('자동차', 'jadongcha'),
  'bus': ('버스', 'beoseu'),
  'train': ('기차', 'gicha'),
  'bicycle': ('자전거', 'jajeongeo'),
  'motorcycle': ('오토바이', 'otobai'),
  'airplane': ('비행기', 'bihaenggi'),
  'station': ('역', 'yeok'),
  'ticket': ('표', 'pyo'),
  'airport': ('공항', 'gonghang'),
  'platform': ('승강장', 'seunggangjang'),
  'schedule': ('시간표', 'siganpyo'),
  'late': ('늦다', 'neutda'),
  'get on': ('올라타다', 'ollatada'),
  'get off': ('내리다', 'naerida'),
  'drive': ('운전하다', 'unjeonhada'),
  'ride': ('타다', 'tada'),
  'stop': ('멈추다', 'meomchuda'),
  'turn': ('돌다', 'dolda'),

  # u15 City & Places
  'city': ('도시', 'dosi'),
  'bank': ('은행', 'eunhaeng'),
  'post office': ('우체국', 'ucheguk'),
  'market': ('시장', 'sijang'),
  'library': ('도서관', 'doseogwan'),
  'park': ('공원', 'gongwon'),
  'cinema': ('영화관', 'yeonghwagwan'),
  'restaurant': ('식당', 'sikdang'),
  'cafe': ('카페', 'kape'),
  'museum': ('박물관', 'bangmulgwan'),
  'beach': ('해변', 'haebyeon'),
  'mall': ('쇼핑몰', 'syopingmol'),
  'left': ('왼쪽', 'oenjjok'),
  'right': ('오른쪽', 'oreunjjok'),
  'straight': ('직진', 'jikjin'),
  'near': ('가깝다', 'gakkapda'),
  'far': ('멀다', 'meolda'),
  'here': ('여기', 'yeogi'),

  # u16 Shopping & Money
  'buy': ('사다', 'sada'),
  'sell': ('팔다', 'palda'),
  'shop': ('가게', 'gage'),
  'money': ('돈', 'don'),
  'price': ('가격', 'gagyeok'),
  'pay': ('지불하다', 'jibulhada'),
  'expensive': ('비싸다', 'bissada'),
  'cheap': ('싸다', 'ssada'),
  'discount': ('할인', 'harin'),
  'free': ('무료', 'muryo'),
  'more': ('더', 'deo'),
  'less': ('덜', 'deol'),
  'cashier': ('계산원', 'gyesanwon'),
  'receipt': ('영수증', 'yeongsujeung'),
  'card': ('카드', 'kadeu'),
  'cash': ('현금', 'hyeongeum'),
  'change': ('잔돈', 'jandon'),
  'wallet': ('지갑', 'jigap'),
}

SENTENCES = {
  # u5
  'I have six apples': ('저는 사과가 여섯 개 있어요', 'jeoneun sagwaga yeoseot gae isseoyo'),
  'Nine plus one is ten': ('아홉 더하기 하나는 열이에요', 'ahop deohagi hananeun yeorieyo'),
  'Twenty people live here': ('여기에 스무 명이 살아요', 'yeogie seumu myeongi sarayo'),
  'The number is fifty': ('숫자는 오십이에요', 'sutjaneun osibieyo'),
  'I am twenty years old': ('저는 스무 살이에요', 'jeoneun seumu sarieyo'),
  'She is the first student': ('그녀는 첫 번째 학생이에요', 'geunyeoneun cheot beonjjae haksaengieyo'),

  # u6
  'The sky is blue': ('하늘은 파란색이에요', 'haneureun paransaegieyo'),
  'My car is red and white': ('제 차는 빨간색과 흰색이에요', 'je chaneun ppalgansaekgwa huinsaegieyo'),
  'The cat is brown': ('고양이는 갈색이에요', 'goyangineun galsaegieyo'),
  'What color do you like': ('어떤 색깔을 좋아해요', 'eotteon saekkkareul joahaeyo'),
  'Green is my favorite color': ('초록색은 제가 가장 좋아하는 색깔이에요', 'choroksaegeun jega gajang joahaneun saekkkarieyo'),
  'The room is dark': ('방이 어두워요', 'bangi eoduwoyo'),

  # u7
  'I have a small dog': ('저는 작은 개가 있어요', 'jeoneun jageun gaega isseoyo'),
  'The cat sleeps on a chair': ('고양이가 의자 위에서 자요', 'goyangiga uija wieseo jayo'),
  'The elephant is very big': ('코끼리는 아주 커요', 'kokkirineun aju keoyo'),
  'Lions eat meat': ('사자는 고기를 먹어요', 'sajaneun gogireul meogeoyo'),
  'The butterfly is beautiful': ('나비가 아름다워요', 'nabiga areumdawoyo'),
  'There are many ants here': ('여기에 개미가 많이 있어요', 'yeogie gaemiga mani isseoyo'),

  # u8
  'Today is Monday': ('오늘은 월요일이에요', 'oneureun woryoirieyo'),
  'I work from Monday to Friday': ('저는 월요일부터 금요일까지 일해요', 'jeoneun woryoilbuteo geumyoilkkaji ilhaeyo'),
  'On Sunday we rest': ('일요일에 우리는 쉬어요', 'iryoire urineun swieoyo'),
  'The weekend is fun': ('주말은 즐거워요', 'jumareun jeulgeowoyo'),
  'I usually drink coffee': ('저는 보통 커피를 마셔요', 'jeoneun botong keopireul masyeoyo'),
  'She never eats meat': ('그녀는 고기를 절대 안 먹어요', 'geunyeoneun gogireul jeoldae an meogeoyo'),

  # u9
  'The weather is sunny today': ('오늘은 날씨가 맑아요', 'oneureun nalssiga malgayo'),
  'It is raining now': ('지금 비가 와요', 'jigeum biga wayo'),
  'I like spring': ('저는 봄을 좋아해요', 'jeoneun bomeul joahaeyo'),
  'It snows in winter': ('겨울에는 눈이 와요', 'gyeoureneun nuni wayo'),
  'It is cold outside': ('밖은 추워요', 'bakkeun chuwoyo'),
  'Bring an umbrella': ('우산을 가져가세요', 'usaneul gajyeogaseyo'),

  # u10
  'My eyes are brown': ('제 눈은 갈색이에요', 'je nuneun galsaegieyo'),
  'Her hair is long': ('그녀의 머리카락은 길어요', 'geunyeoui meorikarageun gireoyo'),
  'Wash your hands': ('손을 씻으세요', 'soneul ssiseuseyo'),
  'My back hurts': ('등이 아파요', 'deungi apayo'),
  'I am sick today': ('저는 오늘 아파요', 'jeoneun oneul apayo'),
  'The doctor gives medicine': ('의사가 약을 줘요', 'uisaga yageul jwoyo'),

  # u11
  'I wear a blue shirt': ('저는 파란 셔츠를 입어요', 'jeoneun paran syeocheureul ibeoyo'),
  'The dress is beautiful': ('그 드레스는 아름다워요', 'geu deureseuneun areumdawoyo'),
  'Where are my shoes': ('제 신발은 어디에 있어요', 'je sinbareun eodie isseoyo'),
  'She wears glasses': ('그녀는 안경을 써요', 'geunyeoneun angyeongeul sseoyo'),
  'This shirt is new': ('이 셔츠는 새 거예요', 'i syeocheuneun sae geoyeyo'),
  'My socks are dirty': ('제 양말이 더러워요', 'je yangmari deoreowoyo'),

  # u12
  'I need a pencil': ('저는 연필이 필요해요', 'jeoneun yeonpiri piryohaeyo'),
  'My book is on the table': ('제 책은 탁자 위에 있어요', 'je chaegeun takja wie isseoyo'),
  'I have homework today': ('저는 오늘 숙제가 있어요', 'jeoneun oneul sukjega isseoyo'),
  'The test is tomorrow': ('시험은 내일이에요', 'siheomeun naeirieyo'),
  'I understand the question': ('저는 질문을 이해해요', 'jeoneun jilmuneul ihaehaeyo'),
  'Please answer in English': ('영어로 대답해 주세요', 'yeongeoro daedaphae juseyo'),

  # u13
  'My father is a farmer': ('제 아버지는 농부예요', 'je abeojineun nongbuyeyo'),
  'The nurse is kind': ('간호사는 친절해요', 'ganhosaneun chinjeolhaeyo'),
  'She wants to be a pilot': ('그녀는 조종사가 되고 싶어해요', 'geunyeoneun jojongsaga doego sipeohaeyo'),
  'The singer is famous': ('그 가수는 유명해요', 'geu gasuneun yumyeonghaeyo'),
  'The meeting is at nine': ('회의는 아홉 시에 있어요', 'hoeuineun ahop sie isseoyo'),
  'I am busy at the office': ('저는 사무실에서 바빠요', 'jeoneun samusireseo bappayo'),

  # u14
  'I go to work by bus': ('저는 버스로 출근해요', 'jeoneun beoseuro chulgeunhaeyo'),
  'The train is fast': ('기차는 빨라요', 'gichaneun ppallayo'),
  'Where is the station': ('역은 어디에 있어요', 'yeogeun eodie isseoyo'),
  'The bus is late': ('버스가 늦어요', 'beoseuga neujeoyo'),
  'Get off at the next stop': ('다음 정류장에서 내리세요', 'daeum jeongnyujangeseo naeriseyo'),
  'Turn left here': ('여기서 왼쪽으로 도세요', 'yeogiseo oenjjogeuro doseyo'),

  # u15
  'Our bank is near the market': ('우리 은행은 시장 근처에 있어요', 'uri eunhaengeun sijang geuncheoe isseoyo'),
  'I read at the library': ('저는 도서관에서 책을 읽어요', 'jeoneun doseogwaneseo chaegeul ilgeoyo'),
  'We watch a movie at the cinema': ('우리는 영화관에서 영화를 봐요', 'urineun yeonghwagwaneseo yeonghwareul bwayo'),
  "Let's go to the beach": ('우리 해변에 가요', 'uri haebyeone gayo'),
  'Go straight and turn right': ('직진해서 오른쪽으로 도세요', 'jikjinhaeseo oreunjjogeuro doseyo'),
  'The school is far from here': ('학교는 여기서 멀어요', 'hakgyoneun yeogiseo meoreoyo'),

  # u16
  'I want to buy bread': ('저는 빵을 사고 싶어요', 'jeoneun ppangeul sago sipeoyo'),
  'How much is the price': ('가격이 얼마예요', 'gagyeogi eolmayeyo'),
  'This bag is too expensive': ('이 가방은 너무 비싸요', 'i gabangeun neomu bissayo'),
  'The shoes are cheap today': ('오늘은 신발이 싸요', 'oneureun sinbari ssayo'),
  'Can I pay by card': ('카드로 지불할 수 있어요', 'kadeuro jibulhal su isseoyo'),
  'Here is your change': ('잔돈 여기 있어요', 'jandon yeogi isseoyo'),
}
