# -*- coding: utf-8 -*-
"""Terjemahan Jerman untuk unit 5-16 (kunci = kata/kalimat Inggris di course_units_master.py)."""

WORDS = {
  # u5 - More Numbers
  'six': ('sechs', 'zeks'),
  'seven': ('sieben', 'zi-ben'),
  'eight': ('acht', 'akht'),
  'nine': ('neun', 'noin'),
  'hundred': ('hundert', 'hun-dert'),
  'zero': ('null', 'nul'),
  'twenty': ('zwanzig', 'tsvan-tsikh'),
  'thirty': ('dreißig', 'drai-sikh'),
  'fifty': ('fünfzig', 'funf-tsikh'),
  'thousand': ('tausend', 'tau-zent'),
  'million': ('die Million', 'di mi-li-on'),
  'number': ('die Zahl', 'di tsal'),
  'age': ('das Alter', 'das al-ter'),
  'year': ('das Jahr', 'das yar'),
  'first': ('erste', 'ers-te'),
  'second': ('zweite', 'tsvai-te'),
  'last': ('letzte', 'lets-te'),
  'old': ('alt', 'alt'),

  # u6 - Colors
  'red': ('rot', 'rot'),
  'blue': ('blau', 'blau'),
  'yellow': ('gelb', 'gelp'),
  'green': ('grün', 'grun'),
  'black': ('schwarz', 'syvarts'),
  'white': ('weiß', 'vais'),
  'orange': ('orange', 'o-rang-sye'),
  'purple': ('lila', 'li-la'),
  'pink': ('rosa', 'ro-za'),
  'brown': ('braun', 'braun'),
  'gray': ('grau', 'grau'),
  'color': ('die Farbe', 'di far-be'),
  'bright': ('hell', 'hel'),
  'dark': ('dunkel', 'dung-kel'),
  'favorite': ('der Favorit', 'der fa-vo-rit'),
  'like': ('mögen', 'mo-gen'),
  'beautiful': ('schön', 'syon'),
  'ugly': ('hässlich', 'hes-likh'),

  # u7 - Animals
  'cat': ('die Katze', 'di ka-tse'),
  'dog': ('der Hund', 'der hunt'),
  'bird': ('der Vogel', 'der fo-gel'),
  'rabbit': ('das Kaninchen', 'das ka-nin-khen'),
  'hamster': ('der Hamster', 'der hams-ter'),
  'pet': ('das Haustier', 'das haus-tir'),
  'elephant': ('der Elefant', 'der e-le-fant'),
  'lion': ('der Löwe', 'der lo-ve'),
  'tiger': ('der Tiger', 'der ti-ger'),
  'horse': ('das Pferd', 'das pfert'),
  'cow': ('die Kuh', 'di ku'),
  'monkey': ('der Affe', 'der a-fe'),
  'frog': ('der Frosch', 'der frosy'),
  'turtle': ('die Schildkröte', 'di sylt-kro-te'),
  'shark': ('der Hai', 'der hai'),
  'butterfly': ('der Schmetterling', 'der syme-ter-ling'),
  'ant': ('die Ameise', 'di a-mai-ze'),
  'mosquito': ('die Mücke', 'di mu-ke'),

  # u8 - Days & Weeks
  'Monday': ('der Montag', 'der mon-tak'),
  'Tuesday': ('der Dienstag', 'der dins-tak'),
  'Wednesday': ('der Mittwoch', 'der mit-vokh'),
  'Thursday': ('der Donnerstag', 'der do-ners-tak'),
  'Friday': ('der Freitag', 'der frai-tak'),
  'day': ('der Tag', 'der tak'),
  'Saturday': ('der Samstag', 'der zams-tak'),
  'Sunday': ('der Sonntag', 'der zon-tak'),
  'weekend': ('das Wochenende', 'das vo-khen-en-de'),
  'week': ('die Woche', 'di vo-khe'),
  'month': ('der Monat', 'der mo-nat'),
  'holiday': ('der Feiertag', 'der fai-er-tak'),
  'always': ('immer', 'i-mer'),
  'usually': ('normalerweise', 'nor-ma-ler-vai-ze'),
  'sometimes': ('manchmal', 'mankh-mal'),
  'never': ('nie', 'ni'),
  'every day': ('jeden Tag', 'ye-den tak'),
  'often': ('oft', 'oft'),

  # u9 - Weather & Seasons
  'weather': ('das Wetter', 'das ve-ter'),
  'sunny': ('sonnig', 'zo-nikh'),
  'cloudy': ('wolkig', 'vol-kikh'),
  'windy': ('windig', 'vin-dikh'),
  'rain': ('der Regen', 'der re-gen'),
  'snow': ('der Schnee', 'der syne'),
  'season': ('die Jahreszeit', 'di ya-res-tsait'),
  'spring': ('der Frühling', 'der fru-ling'),
  'summer': ('der Sommer', 'der zo-mer'),
  'autumn': ('der Herbst', 'der herpst'),
  'winter': ('der Winter', 'der vin-ter'),
  'dry season': ('die Trockenzeit', 'di tro-ken-tsait'),
  'hot': ('heiß', 'hais'),
  'cold': ('kalt', 'kalt'),
  'warm': ('warm', 'varm'),
  'cool': ('kühl', 'kul'),
  'temperature': ('die Temperatur', 'di tem-pe-ra-tur'),
  'umbrella': ('der Regenschirm', 'der re-gen-syirm'),

  # u10 - Body & Health
  'head': ('der Kopf', 'der kopf'),
  'eye': ('das Auge', 'das au-ge'),
  'ear': ('das Ohr', 'das or'),
  'nose': ('die Nase', 'di na-ze'),
  'mouth': ('der Mund', 'der munt'),
  'hair': ('das Haar', 'das har'),
  'hand': ('die Hand', 'di hant'),
  'finger': ('der Finger', 'der fing-er'),
  'foot': ('der Fuß', 'der fus'),
  'arm': ('der Arm', 'der arm'),
  'stomach': ('der Bauch', 'der baukh'),
  'back': ('der Rücken', 'der ru-ken'),
  'sick': ('krank', 'krangk'),
  'healthy': ('gesund', 'ge-zunt'),
  'doctor': ('der Arzt', 'der artst'),
  'medicine': ('die Medizin', 'di me-di-tsin'),
  'hospital': ('das Krankenhaus', 'das krang-ken-haus'),
  'pain': ('der Schmerz', 'der symerts'),

  # u11 - Clothing
  'shirt': ('das Hemd', 'das hemt'),
  'pants': ('die Hose', 'di ho-ze'),
  'dress': ('das Kleid', 'das klait'),
  'skirt': ('der Rock', 'der rok'),
  'jacket': ('die Jacke', 'di ya-ke'),
  'clothes': ('die Kleidung', 'di klai-dung'),
  'hat': ('der Hut', 'der hut'),
  'shoes': ('die Schuhe', 'di syu-e'),
  'socks': ('die Socken', 'di zo-ken'),
  'bag': ('die Tasche', 'di ta-sye'),
  'watch': ('die Armbanduhr', 'di arm-bant-ur'),
  'glasses': ('die Brille', 'di bri-le'),
  'wear': ('tragen', 'tra-gen'),
  'take off': ('ausziehen', 'aus-tsi-en'),
  'size': ('die Größe', 'di gro-se'),
  'new': ('neu', 'noi'),
  'clean': ('sauber', 'zau-ber'),
  'dirty': ('schmutzig', 'symu-tsikh'),

  # u12 - School
  'book': ('das Buch', 'das bukh'),
  'pen': ('der Kugelschreiber', 'der ku-gel-syrai-ber'),
  'pencil': ('der Bleistift', 'der blai-sytift'),
  'paper': ('das Papier', 'das pa-pir'),
  'eraser': ('der Radiergummi', 'der ra-dir-gu-mi'),
  'notebook': ('das Heft', 'das heft'),
  'school': ('die Schule', 'di syu-le'),
  'class': ('die Klasse', 'di kla-se'),
  'classroom': ('das Klassenzimmer', 'das kla-sen-tsi-mer'),
  'homework': ('die Hausaufgaben', 'di haus-auf-ga-ben'),
  'test': ('die Prüfung', 'di pru-fung'),
  'question': ('die Frage', 'di fra-ge'),
  'learn': ('erlernen', 'er-ler-nen'),
  'understand': ('verstehen', 'fer-syte-en'),
  'remember': ('sich erinnern', 'zikh er-i-nern'),
  'forget': ('vergessen', 'fer-ge-sen'),
  'answer': ('antworten', 'ant-vor-ten'),
  'ask': ('fragen', 'fra-gen'),

  # u13 - Work & Jobs
  'job': ('der Beruf', 'der be-ruf'),
  'nurse': ('die Krankenschwester', 'di krang-ken-syves-ter'),
  'police officer': ('der Polizist', 'der po-li-tsist'),
  'farmer': ('der Bauer', 'der bau-er'),
  'cook': ('der Koch', 'der kokh'),
  'driver': ('der Fahrer', 'der fa-rer'),
  'engineer': ('der Ingenieur', 'der in-sye-ni-or'),
  'lawyer': ('der Anwalt', 'der an-valt'),
  'singer': ('der Sänger', 'der zeng-er'),
  'artist': ('der Künstler', 'der kunst-ler'),
  'businessman': ('der Geschäftsmann', 'der ge-syefts-man'),
  'pilot': ('der Pilot', 'der pi-lot'),
  'office': ('das Büro', 'das bu-ro'),
  'meeting': ('die Besprechung', 'di be-sypre-khung'),
  'computer': ('der Computer', 'der kom-pyu-ter'),
  'boss': ('der Chef', 'der syef'),
  'salary': ('das Gehalt', 'das ge-halt'),
  'busy': ('beschäftigt', 'be-syef-tikht'),

  # u14 - Transportation
  'car': ('das Auto', 'das au-to'),
  'bus': ('der Bus', 'der bus'),
  'train': ('der Zug', 'der tsuk'),
  'bicycle': ('das Fahrrad', 'das far-rat'),
  'motorcycle': ('das Motorrad', 'das mo-tor-rat'),
  'airplane': ('das Flugzeug', 'das fluk-tsoik'),
  'station': ('der Bahnhof', 'der ban-hof'),
  'ticket': ('die Fahrkarte', 'di far-kar-te'),
  'airport': ('der Flughafen', 'der fluk-ha-fen'),
  'platform': ('der Bahnsteig', 'der ban-sytaik'),
  'schedule': ('der Fahrplan', 'der far-plan'),
  'late': ('spät', 'sypet'),
  'get on': ('einsteigen', 'ain-sytai-gen'),
  'get off': ('aussteigen', 'aus-sytai-gen'),
  'drive': ('fahren', 'fa-ren'),
  'ride': ('reiten', 'rai-ten'),
  'stop': ('anhalten', 'an-hal-ten'),
  'turn': ('abbiegen', 'ap-bi-gen'),

  # u15 - City & Places
  'city': ('die Stadt', 'di sytat'),
  'bank': ('die Bank', 'di bangk'),
  'post office': ('die Post', 'di post'),
  'market': ('der Markt', 'der markt'),
  'library': ('die Bibliothek', 'di bi-bli-o-tek'),
  'park': ('der Park', 'der park'),
  'cinema': ('das Kino', 'das ki-no'),
  'restaurant': ('das Restaurant', 'das res-to-rang'),
  'cafe': ('das Café', 'das ka-fe'),
  'museum': ('das Museum', 'das mu-ze-um'),
  'beach': ('der Strand', 'der sytrant'),
  'mall': ('das Einkaufszentrum', 'das ain-kaufs-tsen-trum'),
  'left': ('links', 'lingks'),
  'right': ('rechts', 'rekhts'),
  'straight': ('geradeaus', 'ge-ra-de-aus'),
  'near': ('nah', 'na'),
  'far': ('weit', 'vait'),
  'here': ('hier', 'hir'),

  # u16 - Shopping & Money
  'buy': ('kaufen', 'kau-fen'),
  'sell': ('verkaufen', 'fer-kau-fen'),
  'shop': ('das Geschäft', 'das ge-syeft'),
  'money': ('das Geld', 'das gelt'),
  'price': ('der Preis', 'der prais'),
  'pay': ('bezahlen', 'be-tsa-len'),
  'expensive': ('teuer', 'toi-er'),
  'cheap': ('billig', 'bi-likh'),
  'discount': ('der Rabatt', 'der ra-bat'),
  'free': ('kostenlos', 'kos-ten-los'),
  'more': ('mehr', 'mer'),
  'less': ('weniger', 've-ni-ger'),
  'cashier': ('der Kassierer', 'der ka-si-rer'),
  'receipt': ('die Quittung', 'di kvi-tung'),
  'card': ('die Karte', 'di kar-te'),
  'cash': ('das Bargeld', 'das bar-gelt'),
  'change': ('das Wechselgeld', 'das vek-sel-gelt'),
  'wallet': ('die Geldbörse', 'di gelt-bor-ze'),
}

SENTENCES = {
  # u5
  'I have six apples': ('Ich habe sechs Äpfel', 'ikh ha-be zeks ep-fel'),
  'Nine plus one is ten': ('Neun plus eins ist zehn', 'noin plus ains ist tseen'),
  'Twenty people live here': ('Zwanzig Menschen wohnen hier', 'tsvan-tsikh men-syen vo-nen hir'),
  'The number is fifty': ('Die Zahl ist fünfzig', 'di tsal ist funf-tsikh'),
  'I am twenty years old': ('Ich bin zwanzig Jahre alt', 'ikh bin tsvan-tsikh ya-re alt'),
  'She is the first student': ('Sie ist die erste Schülerin', 'zi ist di ers-te syu-le-rin'),

  # u6
  'The sky is blue': ('Der Himmel ist blau', 'der hi-mel ist blau'),
  'My car is red and white': ('Mein Auto ist rot und weiß', 'main au-to ist rot unt vais'),
  'The cat is brown': ('Die Katze ist braun', 'di ka-tse ist braun'),
  'What color do you like': ('Welche Farbe magst du', 'vel-khe far-be makst du'),
  'Green is my favorite color': ('Grün ist meine Lieblingsfarbe', 'grun ist mai-ne lib-lings-far-be'),
  'The room is dark': ('Das Zimmer ist dunkel', 'das tsi-mer ist dung-kel'),

  # u7
  'I have a small dog': ('Ich habe einen kleinen Hund', 'ikh ha-be ai-nen klai-nen hunt'),
  'The cat sleeps on a chair': ('Die Katze schläft auf einem Stuhl', 'di ka-tse syleft auf ai-nem sytul'),
  'The elephant is very big': ('Der Elefant ist sehr groß', 'der e-le-fant ist zer gros'),
  'Lions eat meat': ('Löwen fressen Fleisch', 'lo-ven fre-sen flaisy'),
  'The butterfly is beautiful': ('Der Schmetterling ist schön', 'der syme-ter-ling ist syon'),
  'There are many ants here': ('Hier gibt es viele Ameisen', 'hir gipt es fi-le a-mai-zen'),

  # u8
  'Today is Monday': ('Heute ist Montag', 'hoi-te ist mon-tak'),
  'I work from Monday to Friday': ('Ich arbeite von Montag bis Freitag', 'ikh ar-bai-te fon mon-tak bis frai-tak'),
  'On Sunday we rest': ('Am Sonntag ruhen wir uns aus', 'am zon-tak ru-en vir uns aus'),
  'The weekend is fun': ('Das Wochenende macht Spaß', 'das vo-khen-en-de makht sypas'),
  'I usually drink coffee': ('Ich trinke normalerweise Kaffee', 'ikh tring-ke nor-ma-ler-vai-ze ka-fe'),
  'She never eats meat': ('Sie isst nie Fleisch', 'zi ist ni flaisy'),

  # u9
  'The weather is sunny today': ('Das Wetter ist heute sonnig', 'das ve-ter ist hoi-te zo-nikh'),
  'It is raining now': ('Es regnet jetzt', 'es reg-net yetst'),
  'I like spring': ('Ich mag den Frühling', 'ikh mak den fru-ling'),
  'It snows in winter': ('Im Winter schneit es', 'im vin-ter synait es'),
  'It is cold outside': ('Draußen ist es kalt', 'drau-sen ist es kalt'),
  'Bring an umbrella': ('Nimm einen Regenschirm mit', 'nim ai-nen re-gen-syirm mit'),

  # u10
  'My eyes are brown': ('Meine Augen sind braun', 'mai-ne au-gen zint braun'),
  'Her hair is long': ('Ihr Haar ist lang', 'ir har ist lang'),
  'Wash your hands': ('Wasch dir die Hände', 'vasy dir di hen-de'),
  'My back hurts': ('Mein Rücken tut weh', 'main ru-ken tut ve'),
  'I am sick today': ('Ich bin heute krank', 'ikh bin hoi-te krangk'),
  'The doctor gives medicine': ('Der Arzt gibt Medizin', 'der artst gipt me-di-tsin'),

  # u11
  'I wear a blue shirt': ('Ich trage ein blaues Hemd', 'ikh tra-ge ain blau-es hemt'),
  'The dress is beautiful': ('Das Kleid ist schön', 'das klait ist syon'),
  'Where are my shoes': ('Wo sind meine Schuhe', 'vo zint mai-ne syu-e'),
  'She wears glasses': ('Sie trägt eine Brille', 'zi trekt ai-ne bri-le'),
  'This shirt is new': ('Dieses Hemd ist neu', 'di-zes hemt ist noi'),
  'My socks are dirty': ('Meine Socken sind schmutzig', 'mai-ne zo-ken zint symu-tsikh'),

  # u12
  'I need a pencil': ('Ich brauche einen Bleistift', 'ikh brau-khe ai-nen blai-sytift'),
  'My book is on the table': ('Mein Buch liegt auf dem Tisch', 'main bukh likt auf dem tisy'),
  'I have homework today': ('Ich habe heute Hausaufgaben', 'ikh ha-be hoi-te haus-auf-ga-ben'),
  'The test is tomorrow': ('Die Prüfung ist morgen', 'di pru-fung ist mor-gen'),
  'I understand the question': ('Ich verstehe die Frage', 'ikh fer-syte-e di fra-ge'),
  'Please answer in English': ('Bitte antworte auf Englisch', 'bi-te ant-vor-te auf eng-lisy'),

  # u13
  'My father is a farmer': ('Mein Vater ist Bauer', 'main fa-ter ist bau-er'),
  'The nurse is kind': ('Die Krankenschwester ist freundlich', 'di krang-ken-syves-ter ist froint-likh'),
  'She wants to be a pilot': ('Sie möchte Pilotin werden', 'zi mokh-te pi-lo-tin ver-den'),
  'The singer is famous': ('Der Sänger ist berühmt', 'der zeng-er ist be-rumt'),
  'The meeting is at nine': ('Die Besprechung ist um neun', 'di be-sypre-khung ist um noin'),
  'I am busy at the office': ('Ich bin im Büro beschäftigt', 'ikh bin im bu-ro be-syef-tikht'),

  # u14
  'I go to work by bus': ('Ich fahre mit dem Bus zur Arbeit', 'ikh fa-re mit dem bus tsur ar-bait'),
  'The train is fast': ('Der Zug ist schnell', 'der tsuk ist synel'),
  'Where is the station': ('Wo ist der Bahnhof', 'vo ist der ban-hof'),
  'The bus is late': ('Der Bus hat Verspätung', 'der bus hat fer-sype-tung'),
  'Get off at the next stop': ('Steig an der nächsten Haltestelle aus', 'sytaik an der nekhs-ten hal-te-syte-le aus'),
  'Turn left here': ('Bieg hier links ab', 'bik hir lingks ap'),

  # u15
  'Our bank is near the market': ('Unsere Bank ist nah am Markt', 'un-ze-re bangk ist na am markt'),
  'I read at the library': ('Ich lese in der Bibliothek', 'ikh le-ze in der bi-bli-o-tek'),
  'We watch a movie at the cinema': ('Wir sehen einen Film im Kino', 'vir ze-en ai-nen film im ki-no'),
  "Let's go to the beach": ('Lass uns zum Strand gehen', 'las uns tsum sytrant ge-en'),
  'Go straight and turn right': ('Geh geradeaus und bieg rechts ab', 'ge ge-ra-de-aus unt bik rekhts ap'),
  'The school is far from here': ('Die Schule ist weit von hier', 'di syu-le ist vait fon hir'),

  # u16
  'I want to buy bread': ('Ich möchte Brot kaufen', 'ikh mokh-te brot kau-fen'),
  'How much is the price': ('Wie hoch ist der Preis', 'vi hokh ist der prais'),
  'This bag is too expensive': ('Diese Tasche ist zu teuer', 'di-ze ta-sye ist tsu toi-er'),
  'The shoes are cheap today': ('Die Schuhe sind heute billig', 'di syu-e zint hoi-te bi-likh'),
  'Can I pay by card': ('Kann ich mit Karte bezahlen', 'kan ikh mit kar-te be-tsa-len'),
  'Here is your change': ('Hier ist Ihr Wechselgeld', 'hir ist ir vek-sel-gelt'),
}
