# -*- coding: utf-8 -*-
"""Kosakata tematik Korea (hangul + Romanisasi Revisi) dan Jerman (dengan
artikel + ejaan baca gaya Indonesia), sejajar dengan kursus ja/en/id.

BASE: 3 bagian x (6 kata + 2 kalimat) per tema, dikunci ke kata Inggris
di kursus Inggris. EXTRA: 32 kata tambahan, dikunci ke kata Inggris di
THEMES (gen_vocab_extra.py). Dipakai oleh gen_vocab_extra.py.
"""
# (en_key, ko, rr, de, de_pron)
K = lambda *a: a

BASE = {
 'farming': [
  ('Ladang & Tanaman', 'Fields & Crops', [
    K('farm','농장','nongjang','der Bauernhof','der bau-ern-hof'),
    K('field','밭','bat','das Feld','das felt'),
    K('rice field','논','non','das Reisfeld','das rais-felt'),
    K('crop','농작물','nongjakmul','die Ernte','di ern-te'),
    K('seed','씨앗','ssiat','der Samen','der za-men'),
    K('soil','흙','heuk','die Erde','di er-de'),
    K('The farmer works in the field','농부는 밭에서 일해요','nongbuneun bateseo ilhaeyo','Der Bauer arbeitet auf dem Feld','der bau-er ar-bai-tet auf dem felt'),
    K('We plant seeds in the soil','우리는 흙에 씨앗을 심어요','urineun heulge ssiaseul simeoyo','Wir pflanzen Samen in die Erde','vir pflan-tsen za-men in di er-de'),
  ]),
  ('Menanam & Panen', 'Planting & Harvest', [
    K('to plant','심다','simda','pflanzen','pflan-tsen'),
    K('to grow','키우다','kiuda','anbauen','an-bau-en'),
    K('to water','물을 주다','mureul juda','gießen','gi-sen'),
    K('harvest','수확','suhwak','die Ernte (Vorgang)','di ern-te'),
    K('fertilizer','비료','biryo','der Dünger','der dyng-er'),
    K('tractor','트랙터','teuraekteo','der Traktor','der trak-tor'),
    K('I grow vegetables at home','저는 집에서 채소를 키워요','jeoneun jibeseo chaesoreul kiwoyo','Ich baue zu Hause Gemüse an','ikh bau-e tsu hau-ze ge-my-ze an'),
    K('We water the plants every morning','우리는 매일 아침 식물에 물을 줘요','urineun maeil achim singmure mureul jwoyo','Wir gießen die Pflanzen jeden Morgen','vir gi-sen di pflan-tsen ye-den mor-gen'),
  ]),
  ('Peternakan', 'Livestock', [
    K('cattle','소','so','das Rind','das rint'),
    K('chicken','닭','dak','das Huhn','das hun'),
    K('sheep','양','yang','das Schaf','das syaf'),
    K('goat','염소','yeomso','die Ziege','di tsi-ge'),
    K('honey','꿀','kkul','der Honig','der ho-nikh'),
    K('barn','축사','chuksa','der Stall','der sytal'),
    K('The chickens lay eggs every day','닭은 매일 알을 낳아요','dalgeun maeil areul nayo','Die Hühner legen jeden Tag Eier','di hy-ner le-gen ye-den tak ai-er'),
    K('There are cows in the barn','축사에 소가 있어요','chuksae soga isseoyo','Im Stall sind Kühe','im sytal zint ky-e'),
  ]),
 ],
 'sea': [
  ('Pelaut & Kapal', 'Sailors & Ships', [
    K('sailor','선원','seonwon','der Seemann','der ze-man'),
    K('harbor','항구','hanggu','der Hafen','der ha-fen'),
    K('ship','배','bae','das Schiff','das syif'),
    K('wave','파도','pado','die Welle','di ve-le'),
    K('beach','해변','haebyeon','der Strand','der syrant'),
    K('lighthouse','등대','deungdae','der Leuchtturm','der loikht-turm'),
    K('The ship is in the harbor','배가 항구에 있어요','baega hanggue isseoyo','Das Schiff ist im Hafen','das syif ist im ha-fen'),
    K('The waves are high today','오늘은 파도가 높아요','oneureun padoga nopayo','Die Wellen sind heute hoch','di ve-len zint hoi-te hokh'),
  ]),
  ('Menangkap Ikan', 'Fishing', [
    K('fisherman','어부','eobu','der Fischer','der fi-syer'),
    K('net','그물','geumul','das Netz','das nets'),
    K('tuna','참치','chamchi','der Thunfisch','der tun-fisy'),
    K('shrimp','새우','saeu','die Garnele','di gar-ne-le'),
    K('crab','게','ge','die Krabbe','di kra-be'),
    K('octopus','문어','muneo','der Oktopus','der ok-to-pus'),
    K('Fishermen go to sea early in the morning','어부들은 이른 아침에 바다에 나가요','eobudeureun ireun achime badae nagayo','Fischer fahren früh am Morgen aufs Meer','fi-syer fa-ren fry am mor-gen aufs mer'),
    K('He caught a big tuna','그는 큰 참치를 잡았어요','geuneun keun chamchireul jabasseoyo','Er hat einen großen Thunfisch gefangen','er hat ai-nen gro-sen tun-fisy ge-fang-en'),
  ]),
  ('Bawah Laut', 'Under the Sea', [
    K('shell','조개','jogae','die Muschel','di mu-syel'),
    K('coral','산호','sanho','die Koralle','di ko-ra-le'),
    K('diving','다이빙','daibing','das Tauchen','das tau-khen'),
    K('deep','깊다','gipda','tief','tif'),
    K('shallow','얕다','yatda','flach','flakh'),
    K('aquarium','수족관','sujokgwan','das Aquarium','das a-kva-ri-um'),
    K('The sea is very deep here','여기는 바다가 아주 깊어요','yeogineun badaga aju gipeoyo','Das Meer ist hier sehr tief','das mer ist hir zer tif'),
    K('We watch fish at the aquarium','우리는 수족관에서 물고기를 봐요','urineun sujokgwaneseo mulgogireul bwayo','Wir sehen Fische im Aquarium','vir ze-en fi-sye im a-kva-ri-um'),
  ]),
 ],
 'office': [
  ('Orang Kantor', 'Office People', [
    K('boss','사장님','sajangnim','der Chef','der syef'),
    K('manager','매니저','maenijeo','der Manager','der me-ne-jer'),
    K('employee','직원','jigwon','der Angestellte','der an-ge-syytel-te'),
    K('colleague','동료','dongnyo','der Kollege','der ko-le-ge'),
    K('part-time job','아르바이트','areubaiteu','der Nebenjob','der ne-ben-job'),
    K('interview','면접','myeonjeop','das Vorstellungsgespräch','das for-syte-lungs-ge-syprekh'),
    K('My boss is very busy','사장님은 아주 바빠요','sajangnimeun aju bappayo','Mein Chef ist sehr beschäftigt','main syef ist zer be-syef-tikht'),
    K('I have a job interview tomorrow','내일 면접이 있어요','naeil myeonjeobi isseoyo','Ich habe morgen ein Vorstellungsgespräch','ikh ha-be mor-gen ain for-syte-lungs-ge-syprekh'),
  ]),
  ('Di Meja Kerja', 'At the Desk', [
    K('document','서류','seoryu','das Dokument','das do-ku-ment'),
    K('meeting room','회의실','hoeuisil','der Besprechungsraum','der be-syprekh-ungs-raum'),
    K('printer','프린터','peurinteo','der Drucker','der dru-ker'),
    K('signature','서명','seomyeong','die Unterschrift','di un-ter-syrift'),
    K('photocopy','복사','boksa','die Kopie','di ko-pi'),
    K('deadline','마감','magam','die Frist','di frist'),
    K('Please sign the document','서류에 서명해 주세요','seoryue seomyeonghae juseyo','Bitte unterschreiben Sie das Dokument','bi-te un-ter-syrai-ben zi das do-ku-ment'),
    K('The meeting starts at nine','회의는 아홉 시에 시작해요','hoeuineun ahop sie sijakaeyo','Die Besprechung beginnt um neun','di be-syprekh-ung be-gint um noin'),
  ]),
  ('Gaji & Karier', 'Salary & Career', [
    K('salary','월급','wolgeup','das Gehalt','das ge-halt'),
    K('overtime','야근','yageun','die Überstunden','di y-ber-syytun-den'),
    K('paid leave','유급 휴가','yugeup hyuga','der Urlaub','der ur-laup'),
    K('business trip','출장','chuljang','die Dienstreise','di dinst-rai-ze'),
    K('promotion','승진','seungjin','die Beförderung','di be-fer-de-rung'),
    K('retirement','은퇴','euntoe','der Ruhestand','der ru-e-syytant'),
    K('She got a promotion last month','그녀는 지난달에 승진했어요','geunyeoneun jinandare seungjinhaesseoyo','Sie wurde letzten Monat befördert','zi vur-de lets-ten mo-nat be-fer-dert'),
    K('I have a business trip next week','다음 주에 출장이 있어요','daeum jue chuljangi isseoyo','Ich habe nächste Woche eine Dienstreise','ikh ha-be nekhs-te vo-khe ai-ne dinst-rai-ze'),
  ]),
 ],
 'cooking': [
  ('Cara Memasak', 'Cooking Methods', [
    K('to bake','굽다 (오븐)','gupda (obeun)','backen','ba-ken'),
    K('to fry','튀기다','twigida','frittieren','fri-ti-ren'),
    K('to boil','삶다','samda','kochen','ko-khen'),
    K('to steam','찌다','jjida','dämpfen','demp-fen'),
    K('to grill','굽다 (그릴)','gupda (geuril)','grillen','gri-len'),
    K('to mix','섞다','seokda','mischen','mi-syen'),
    K('I boil the eggs for ten minutes','저는 달걀을 십 분 동안 삶아요','jeoneun dalgyareul sip bun dongan salmayo','Ich koche die Eier zehn Minuten','ikh ko-khe di ai-er tsen mi-nu-ten'),
    K('She bakes bread every weekend','그녀는 주말마다 빵을 구워요','geunyeoneun jumalmada ppangeul guwoyo','Sie backt jedes Wochenende Brot','zi bakt ye-des vo-khen-en-de brot'),
  ]),
  ('Bumbu', 'Seasonings', [
    K('sugar','설탕','seoltang','der Zucker','der tsu-ker'),
    K('salt','소금','sogeum','das Salz','das zalts'),
    K('pepper','후추','huchu','der Pfeffer','der pfe-fer'),
    K('cooking oil','식용유','sigyongyu','das Speiseöl','das syypai-ze-el'),
    K('soy sauce','간장','ganjang','die Sojasauce','di zo-ya-zo-se'),
    K('garlic','마늘','maneul','der Knoblauch','der knop-laukh'),
    K('Add a little salt','소금을 조금 넣어요','sogeumeul jogeum neoeoyo','Gib ein bisschen Salz dazu','gip ain bis-khen zalts da-tsu'),
    K('This soup needs more pepper','이 수프는 후추가 더 필요해요','i supeuneun huchuga deo piryohaeyo','Diese Suppe braucht mehr Pfeffer','di-ze zu-pe braukht mer pfe-fer'),
  ]),
  ('Peralatan Dapur', 'Kitchen Tools', [
    K('knife','칼','kal','das Messer','das me-ser'),
    K('pot','냄비','naembi','der Topf','der topf'),
    K('frying pan','프라이팬','peuraipaen','die Pfanne','di pfa-ne'),
    K('plate','접시','jeopsi','der Teller','der te-ler'),
    K('glass','컵','keop','das Glas','das glas'),
    K('spoon','숟가락','sutgarak','der Löffel','der le-fel'),
    K('Cut the vegetables with a knife','칼로 채소를 썰어요','kallo chaesoreul sseoreoyo','Schneide das Gemüse mit dem Messer','synai-de das ge-my-ze mit dem me-ser'),
    K('The plates are on the table','접시는 식탁 위에 있어요','jeopsineun siktak wie isseoyo','Die Teller sind auf dem Tisch','di te-ler zint auf dem tisy'),
  ]),
 ],
 'tools': [
  ('Perkakas', 'Tools', [
    K('hammer','망치','mangchi','der Hammer','der ha-mer'),
    K('nail','못','mot','der Nagel','der na-gel'),
    K('screw','나사','nasa','die Schraube','di syrau-be'),
    K('screwdriver','드라이버','deuraibeo','der Schraubenzieher','der syrau-ben-tsi-er'),
    K('saw','톱','top','die Säge','di ze-ge'),
    K('ladder','사다리','sadari','die Leiter','di lai-ter'),
    K('Hit the nail with a hammer','망치로 못을 쳐요','mangchiro moseul chyeoyo','Schlag den Nagel mit dem Hammer','syylak den na-gel mit dem ha-mer'),
    K('He cuts the wood with a saw','그는 톱으로 나무를 잘라요','geuneun tobeuro namureul jallayo','Er sägt das Holz mit der Säge','er zekt das holts mit der ze-ge'),
  ]),
  ('Di Lokasi Bangunan', 'At the Site', [
    K('construction','건설','geonseol','der Bau','der bau'),
    K('worker','노동자','nodongja','der Arbeiter','der ar-bai-ter'),
    K('helmet','헬멧','helmet','der Helm','der helm'),
    K('machine','기계','gigye','die Maschine','di ma-syi-ne'),
    K('brick','벽돌','byeokdol','der Ziegel','der tsi-gel'),
    K('cement','시멘트','simenteu','der Zement','der tse-ment'),
    K('Please wear a helmet here','여기서는 헬멧을 써 주세요','yeogiseoneun helmeseul sseo juseyo','Bitte tragen Sie hier einen Helm','bi-te tra-gen zi hir ai-nen helm'),
    K('The workers build a new school','노동자들이 새 학교를 지어요','nodongjadeuri sae hakgyoreul jieoyo','Die Arbeiter bauen eine neue Schule','di ar-bai-ter bau-en ai-ne noi-e syu-le'),
  ]),
  ('Membangun', 'Building', [
    K('to build','짓다','jitda','bauen','bau-en'),
    K('to fix','고치다','gochida','reparieren','re-pa-ri-ren'),
    K('broken','고장 나다','gojang nada','kaputt','ka-put'),
    K('paint','페인트','peinteu','die Farbe','di far-be'),
    K('wood','나무','namu','das Holz','das holts'),
    K('wall','벽','byeok','die Wand','di vant'),
    K('They build houses','그들은 집을 지어요','geudeureun jibeul jieoyo','Sie bauen Häuser','zi bau-en hoi-zer'),
    K('My father fixes the roof','아버지는 지붕을 고쳐요','abeojineun jibungeul gochyeoyo','Mein Vater repariert das Dach','main fa-ter re-pa-rirt das dakh'),
  ]),
 ],
 'economy': [
  ('Di Bank', 'At the Bank', [
    K('bank account','은행 계좌','eunhaeng gyejwa','das Bankkonto','das bank-kon-to'),
    K('savings','저축','jeochuk','die Ersparnisse','di er-syypar-ni-se'),
    K('to withdraw','출금하다','chulgeumhada','abheben','ap-he-ben'),
    K('to deposit','입금하다','ipgeumhada','einzahlen','ain-tsa-len'),
    K('transfer','송금','songgeum','die Überweisung','di y-ber-vai-zung'),
    K('interest','이자','ija','die Zinsen','di tsin-zen'),
    K('I open a bank account','저는 은행 계좌를 열어요','jeoneun eunhaeng gyejwareul yeoreoyo','Ich eröffne ein Bankkonto','ikh er-ef-ne ain bank-kon-to'),
    K('She withdraws money at the ATM','그녀는 ATM에서 돈을 출금해요','geunyeoneun ATM-eseo doneul chulgeumhaeyo','Sie hebt Geld am Automaten ab','zi hept gelt am au-to-ma-ten ap'),
  ]),
  ('Ekonomi', 'The Economy', [
    K('economy','경제','gyeongje','die Wirtschaft','di virt-syaft'),
    K('market','시장','sijang','der Markt','der markt'),
    K('tax','세금','segeum','die Steuer','di syytoi-er'),
    K('price','가격','gagyeok','der Preis','der prais'),
    K('discount','할인','harin','der Rabatt','der ra-bat'),
    K('stock','주식','jusik','die Aktie','di ak-tsi-e'),
    K('Prices go up every year','가격은 매년 올라요','gagyeogeun maenyeon ollayo','Die Preise steigen jedes Jahr','di prai-ze syytai-gen ye-des yar'),
    K('This shop gives a big discount','이 가게는 할인을 많이 해 줘요','i gageneun harineul mani hae jwoyo','Dieser Laden gibt einen großen Rabatt','di-zer la-den gipt ai-nen gro-sen ra-bat'),
  ]),
  ('Jual Beli', 'Trade', [
    K('export','수출','suchul','der Export','der eks-port'),
    K('import','수입','suip','der Import','der im-port'),
    K('trade','무역','muyeok','der Handel','der han-del'),
    K('profit','이익','iik','der Gewinn','der ge-vin'),
    K('loss','손해','sonhae','der Verlust','der fer-lust'),
    K('customer','고객','gogaek','der Kunde','der kun-de'),
    K('Indonesia exports coffee','인도네시아는 커피를 수출해요','indonesianeun keopireul suchulhaeyo','Indonesien exportiert Kaffee','in-do-ne-zi-en eks-por-tirt ka-fe'),
    K('The customer is always right','고객은 항상 옳아요','gogaegeun hangsang orayo','Der Kunde hat immer recht','der kun-de hat i-mer rekht'),
  ]),
 ],
 'science': [
  ('Sains Dasar', 'Basic Science', [
    K('science','과학','gwahak','die Wissenschaft','di vi-sen-syaft'),
    K('experiment','실험','silheom','das Experiment','das eks-pe-ri-ment'),
    K('research','연구','yeongu','die Forschung','di for-syung'),
    K('discovery','발견','balgyeon','die Entdeckung','di ent-de-kung'),
    K('laboratory','실험실','silheomsil','das Labor','das la-bor'),
    K('mathematics','수학','suhak','die Mathematik','di ma-te-ma-tik'),
    K('We do an experiment at school','우리는 학교에서 실험을 해요','urineun hakgyoeseo silheomeul haeyo','Wir machen ein Experiment in der Schule','vir ma-khen ain eks-pe-ri-ment in der syu-le'),
    K('Math is my favorite subject','수학은 제가 가장 좋아하는 과목이에요','suhageun jega gajang joahaneun gwamogieyo','Mathe ist mein Lieblingsfach','ma-te ist main lip-lings-fakh'),
  ]),
  ('Luar Angkasa', 'Outer Space', [
    K('space','우주','uju','der Weltraum','der velt-raum'),
    K('the Earth','지구','jigu','die Erde (Planet)','di er-de'),
    K('planet','행성','haengseong','der Planet','der pla-net'),
    K('rocket','로켓','roket','die Rakete','di ra-ke-te'),
    K('astronaut','우주 비행사','uju bihaengsa','der Astronaut','der as-tro-naut'),
    K('shooting star','별똥별','byeolttongbyeol','die Sternschnuppe','di syytern-synu-pe'),
    K('The Earth is a planet','지구는 행성이에요','jiguneun haengseongieyo','Die Erde ist ein Planet','di er-de ist ain pla-net'),
    K('The rocket flies to space','로켓이 우주로 날아가요','rokesi ujuro naragayo','Die Rakete fliegt ins Weltall','di ra-ke-te flikt ins velt-al'),
  ]),
  ('Mengukur', 'Measuring', [
    K('to measure','측정하다','cheukjeonghada','messen','me-sen'),
    K('length','길이','giri','die Länge','di leng-e'),
    K('weight','무게','muge','das Gewicht','das ge-vikht'),
    K('speed','속도','sokdo','die Geschwindigkeit','di ge-syvin-dikh-kait'),
    K('temperature','온도','ondo','die Temperatur','di tem-pe-ra-tur'),
    K('battery','배터리','baeteori','die Batterie','di ba-te-ri'),
    K('I measure the temperature','저는 온도를 측정해요','jeoneun ondoreul cheukjeonghaeyo','Ich messe die Temperatur','ikh me-se di tem-pe-ra-tur'),
    K('The battery is empty','배터리가 다 됐어요','baeteoriga da dwaesseoyo','Die Batterie ist leer','di ba-te-ri ist ler'),
  ]),
 ],
 'industry': [
  ('Di Pabrik', 'At the Factory', [
    K('factory','공장','gongjang','die Fabrik','di fa-brik'),
    K('product','제품','jepum','das Produkt','das pro-dukt'),
    K('robot','로봇','robot','der Roboter','der ro-bo-ter'),
    K('parts','부품','bupum','die Teile','di tai-le'),
    K('production line','생산 라인','saengsan rain','das Fließband','das flis-bant'),
    K('inspection','검사','geomsa','die Prüfung','di pry-fung'),
    K('This factory makes cars','이 공장은 자동차를 만들어요','i gongjangeun jadongchareul mandeureoyo','Diese Fabrik baut Autos','di-ze fa-brik baut au-tos'),
    K('Robots work day and night','로봇은 밤낮으로 일해요','roboseun bamnajeuro ilhaeyo','Roboter arbeiten Tag und Nacht','ro-bo-ter ar-bai-ten tak unt nakht'),
  ]),
  ('Produksi', 'Production', [
    K('production','생산','saengsan','die Produktion','di pro-duk-tsion'),
    K('quality','품질','pumjil','die Qualität','di kva-li-tet'),
    K('efficiency','효율','hyoyul','die Effizienz','di e-fi-tsi-ents'),
    K('safety','안전','anjeon','die Sicherheit','di zi-kher-hait'),
    K('warning','경고','gyeonggo','die Warnung','di var-nung'),
    K('break','휴식','hyusik','die Pause','di pau-ze'),
    K('The quality is very good','품질이 아주 좋아요','pumjiri aju joayo','Die Qualität ist sehr gut','di kva-li-tet ist zer gut'),
    K("Let's take a short break",'잠깐 쉬어요','jamkkan swieoyo','Machen wir eine kurze Pause','ma-khen vir ai-ne kur-tse pau-ze'),
  ]),
  ('Energi', 'Energy', [
    K('energy','에너지','eneoji','die Energie','di e-ner-gi'),
    K('oil','석유','seogyu','das Erdöl','das ert-el'),
    K('gas','가스','gaseu','das Gas','das gas'),
    K('solar power','태양광','taeyanggwang','die Solarenergie','di zo-lar-e-ner-gi'),
    K('electricity','전기','jeongi','der Strom','der syytrom'),
    K('resources','자원','jawon','die Ressourcen','di re-sur-sen'),
    K('The electricity comes from solar power','전기는 태양광에서 나와요','jeongineun taeyanggwangeseo nawayo','Der Strom kommt aus Solarenergie','der syytrom komt aus zo-lar-e-ner-gi'),
    K('We must save energy','우리는 에너지를 절약해야 해요','urineun eneojireul jeoryakaeya haeyo','Wir müssen Energie sparen','vir my-sen e-ner-gi sypa-ren'),
  ]),
 ],
}

# en_key -> (ko, rr, de, de_pron)
EXTRA = {
 # farming
 'farmer':('농부','nongbu','der Bauer','der bau-er'), 'sprinkler':('스프링클러','seupeuringkeulleo','der Sprinkler','der syprink-ler'),
 'hoe':('괭이','gwaengi','die Hacke','di ha-ke'), 'sickle':('낫','nat','die Sichel','di zi-khel'),
 'shovel':('삽','sap','die Schaufel','di syau-fel'), 'wheelbarrow':('외바퀴 손수레','oebakwi sonsure','die Schubkarre','di syup-ka-re'),
 'irrigation':('관개','gwangae','die Bewässerung','di be-ve-se-rung'), 'granary':('곡물 창고','gongmul changgo','der Speicher','der syypai-kher'),
 'vegetable':('채소','chaeso','das Gemüse','das ge-my-ze'), 'fruit':('과일','gwail','das Obst','das opst'),
 'corn':('옥수수','oksusu','der Mais','der mais'), 'potato':('감자','gamja','die Kartoffel','di kar-to-fel'),
 'carrot':('당근','danggeun','die Karotte','di ka-ro-te'), 'tomato':('토마토','tomato','die Tomate','di to-ma-te'),
 'apple':('사과','sagwa','der Apfel','der ap-fel'), 'soybean':('콩','kong','die Sojabohne','di zo-ya-bo-ne'),
 'rain':('비','bi','der Regen','der re-gen'), 'drought':('가뭄','gamum','die Dürre','di dy-re'),
 'season':('계절','gyejeol','die Jahreszeit','di ya-res-tsait'), 'rainy season':('장마','jangma','die Regenzeit','di re-gen-tsait'),
 'sunlight':('햇빛','haetbit','das Sonnenlicht','das zo-nen-likht'), 'wind':('바람','baram','der Wind','der vint'),
 'flood':('홍수','hongsu','die Überschwemmung','di y-ber-syve-mung'), 'pest':('해충','haechung','der Schädling','der syet-ling'),
 'cow':('암소','amso','die Kuh','di ku'), 'pig':('돼지','dwaeji','das Schwein','das syvain'),
 'duck':('오리','ori','die Ente','di en-te'), 'egg':('달걀','dalgyal','das Ei','das ai'),
 'milk':('우유','uyu','die Milch','di milkh'), 'animal feed':('사료','saryo','das Futter','das fu-ter'),
 'pasture':('목초지','mokchoji','die Weide','di vai-de'), 'straw':('짚','jip','das Stroh','das syytro'),
 # sea
 'pier':('부두','budu','der Pier','der pir'), 'anchor':('닻','dat','der Anker','der ang-ker'),
 'shipyard':('조선소','joseonso','die Werft','di verft'), 'diver':('잠수부','jamsubu','der Taucher','der tau-kher'),
 'captain':('선장','seonjang','der Kapitän','der ka-pi-ten'), 'crew':('승무원','seungmuwon','die Besatzung','di be-za-tsung'),
 'ferry':('여객선','yeogaekseon','die Fähre','di fe-re'), 'sail':('돛','dot','das Segel','das ze-gel'),
 'harpoon':('작살','jaksal','die Harpune','di har-pu-ne'), 'hook':('낚싯바늘','naksitbaneul','der Haken','der ha-ken'),
 'bait':('미끼','mikki','der Köder','der ke-der'), 'fishing rod':('낚싯대','naksitdae','die Angel','di ang-el'),
 'buoy':('부표','bupyo','die Boje','di bo-ye'), 'trap':('통발','tongbal','die Falle','di fa-le'),
 'rope':('밧줄','batjul','das Seil','das zail'), 'bucket':('양동이','yangdongi','der Eimer','der ai-mer'),
 'fish':('물고기','mulgogi','der Fisch','der fisy'), 'starfish':('불가사리','bulgasari','der Seestern','der ze-syytern'),
 'jellyfish':('해파리','haepari','die Qualle','di kva-le'), 'squid':('오징어','ojingeo','der Tintenfisch','der tin-ten-fisy'),
 'sea turtle':('바다거북','badageobuk','die Meeresschildkröte','di me-res-syilt-kre-te'), 'dolphin':('돌고래','dolgorae','der Delfin','der del-fin'),
 'shark':('상어','sangeo','der Hai','der hai'), 'whale':('고래','gorae','der Wal','der val'),
 'fog':('안개','angae','der Nebel','der ne-bel'), 'high tide':('만조','manjo','die Flut','di flut'),
 'low tide':('간조','ganjo','die Ebbe','di e-be'), 'storm':('폭풍','pokpung','der Sturm','der syyturm'),
 'ocean current':('해류','haeryu','die Meeresströmung','di me-res-syytre-mung'), 'bay':('만','man','die Bucht','di bukht'),
 'island':('섬','seom','die Insel','di in-zel'), 'seaweed':('해초','haecho','der Seetang','der ze-tang'),
 # office
 'meeting':('회의','hoeui','die Besprechung','di be-syprekh-ung'), 'schedule':('일정','iljeong','der Zeitplan','der tsait-plan'),
 'reminder':('알림','allim','die Erinnerung','di er-i-ne-rung'), 'report':('보고서','bogoseo','der Bericht','der be-rikht'),
 'presentation':('발표','balpyo','die Präsentation','di pre-zen-ta-tsion'), 'agenda':('안건','angeon','die Tagesordnung','di ta-ges-ort-nung'),
 'receptionist':('접수 직원','jeopsu jigwon','die Empfangskraft','di emp-fangs-kraft'), 'minutes (notes)':('회의록','hoeuirok','das Protokoll','das pro-to-kol'),
 'computer':('컴퓨터','keompyuteo','der Computer','der kom-pyu-ter'), 'photocopier':('복사기','boksagi','der Kopierer','der ko-pi-rer'),
 'stapler':('스테이플러','seuteipeulleo','der Tacker','der ta-ker'), 'folder':('폴더','poldeo','der Ordner','der ort-ner'),
 'paper clip':('클립','keullip','die Büroklammer','di by-ro-kla-mer'), 'calendar':('달력','dallyeok','der Kalender','der ka-len-der'),
 'ballpoint pen':('볼펜','bolpen','der Kugelschreiber','der ku-gel-syrai-ber'), 'paper':('종이','jongi','das Papier','das pa-pir'),
 'email':('이메일','imeil','die E-Mail','di i-meil'), 'phone call':('전화','jeonhwa','der Anruf','der an-ruf'),
 'message':('메시지','mesiji','die Nachricht','di nakh-rikht'), 'client':('고객사','gogaeksa','der Klient','der kli-ent'),
 'visitor':('방문객','bangmungaek','der Besucher','der be-zu-kher'), 'business card':('명함','myeongham','die Visitenkarte','di vi-zi-ten-kar-te'),
 'online meeting':('온라인 회의','onrain hoeui','die Online-Besprechung','di on-lain-be-syprekh-ung'), 'absence':('결근','gyeolgeun','die Abwesenheit','di ap-ve-zen-hait'),
 'resume (CV)':('이력서','iryeokseo','der Lebenslauf','der le-bens-lauf'), 'job application':('입사 지원','ipsa jiwon','die Bewerbung','di be-ver-bung'),
 'performance review':('인사 평가','insa pyeongga','die Leistungsbeurteilung','di lais-tungs-be-ur-tai-lung'), 'contract':('계약','gyeyak','der Vertrag','der fer-trak'),
 'internship':('인턴십','inteonsip','das Praktikum','das prak-ti-kum'), 'job transfer':('전근','jeongeun','die Versetzung','di fer-ze-tsung'),
 'training':('연수','yeonsu','die Schulung','di syu-lung'), 'allowance':('수당','sudang','die Zulage','di tsu-la-ge'),
 # cooking
 'flour':('밀가루','milgaru','das Mehl','das mel'), 'butter':('버터','beoteo','die Butter','di bu-ter'),
 'yeast':('이스트','iseuteu','die Hefe','di he-fe'), 'chocolate':('초콜릿','chokollit','die Schokolade','di syo-ko-la-de'),
 'cooked rice':('밥','bap','der Reis (gekocht)','der rais'), 'noodles':('면','myeon','die Nudeln','di nu-deln'),
 'sweet':('달다','dalda','süß','zys'), 'salty':('짜다','jjada','salzig','zal-tsikh'),
 'spicy':('맵다','maepda','scharf','syarf'), 'sour':('시다','sida','sauer','zau-er'),
 'bitter':('쓰다','sseuda','bitter','bi-ter'), 'savory':('감칠맛','gamchilmat','herzhaft','herts-haft'),
 'crispy':('바삭하다','basakada','knusprig','knus-prikh'), 'tender':('부드럽다','budeureopda','zart','tsart'),
 'stove':('가스레인지','gaseureinji','der Herd','der hert'), 'oven':('오븐','obeun','der Backofen','der bak-o-fen'),
 'refrigerator':('냉장고','naengjanggo','der Kühlschrank','der kyl-syrank'), 'cutting board':('도마','doma','das Schneidebrett','das synai-de-bret'),
 'spatula':('뒤집개','dwijipgae','der Pfannenwender','der pfa-nen-ven-der'), 'fork':('포크','pokeu','die Gabel','di ga-bel'),
 'bowl':('그릇','geureut','die Schüssel','di syy-sel'), 'kettle':('주전자','jujeonja','der Wasserkocher','der va-ser-ko-kher'),
 'to cut':('자르다','jareuda','schneiden','synai-den'), 'to peel':('껍질을 벗기다','kkeopjireul beotgida','schälen','sye-len'),
 'to taste':('맛보다','matboda','probieren','pro-bi-ren'), 'to serve':('차리다','charida','servieren','zer-vi-ren'),
 'recipe':('레시피','resipi','das Rezept','das re-tsept'), 'serving':('일인분','irinbun','die Portion','di por-tsion'),
 'breakfast':('아침 식사','achim siksa','das Frühstück','das fry-syytyk'), 'dinner':('저녁 식사','jeonyeok siksa','das Abendessen','das a-bent-e-sen'),
 # tools
 'file (tool)':('줄','jul','die Feile','di fai-le'), 'crowbar':('쇠지렛대','soejiretdae','die Brechstange','di brekh-syytang-e'),
 'pliers':('펜치','penchi','die Zange','di tsang-e'), 'wrench':('렌치','renchi','der Schraubenschlüssel','der syrau-ben-syly-sel'),
 'chisel':('끌','kkeul','der Meißel','der mai-sel'), 'mallet':('나무망치','namumangchi','der Holzhammer','der holts-ha-mer'),
 'drill':('드릴','deuril','die Bohrmaschine','di bor-ma-syi-ne'), 'tape measure':('줄자','julja','das Maßband','das mas-bant'),
 'bamboo':('대나무','daenamu','der Bambus','der bam-bus'), 'steel':('강철','gangcheol','der Stahl','der syytal'),
 'iron':('철','cheol','das Eisen','das ai-zen'), 'sand':('모래','morae','der Sand','der zant'),
 'tile':('타일','tail','die Fliese','di fli-ze'), 'glass':('유리','yuri','das Glas (Material)','das glas'),
 'plastic':('플라스틱','peullaseutik','der Kunststoff','der kunst-syytof'), 'varnish':('니스','niseu','der Lack','der lak'),
 'rivet':('리벳','ribet','der Niet','der nit'), 'bolt':('볼트','bolteu','der Bolzen','der bol-tsen'),
 'nut (hardware)':('너트','neoteu','die Mutter (Schraube)','di mu-ter'), 'glue':('접착제','jeopchakje','der Kleber','der kle-ber'),
 'tack':('압정','apjeong','die Reißzwecke','di rais-tsve-ke'), 'hinge':('경첩','gyeongcheop','das Scharnier','das syar-nir'),
 'wire':('철사','cheolsa','der Draht','der drat'), 'tape':('테이프','teipeu','das Klebeband','das kle-be-bant'),
 'safety vest':('안전 조끼','anjeon jokki','die Warnweste','di varn-ves-te'), 'gloves':('장갑','janggap','die Handschuhe','di hant-syu-e'),
 'safety goggles':('보호 안경','boho angyeong','die Schutzbrille','di syuts-bri-le'), 'scaffolding':('비계','bigye','das Gerüst','das ge-ryst'),
 'workshop':('작업장','jageopjang','die Werkstatt','di verk-syytat'), 'to sharpen':('갈다','galda','schärfen','syer-fen'),
 'to install':('설치하다','seolchihada','installieren','in-sta-li-ren'), 'to tighten':('조이다','joida','festziehen','fest-tsi-en'),
 # economy
 'money':('돈','don','das Geld','das gelt'), 'wallet':('지갑','jigap','die Geldbörse','di gelt-ber-ze'),
 'cash':('현금','hyeongeum','das Bargeld','das bar-gelt'), 'fee':('수수료','susuryo','die Gebühr','di ge-byr'),
 'change (money)':('잔돈','jandon','das Wechselgeld','das vek-sel-gelt'), 'bill (invoice)':('청구서','cheongguseo','die Rechnung','di rekh-nung'),
 'receipt':('영수증','yeongsujeung','der Kassenbon','der ka-sen-bong'), 'currency':('통화','tonghwa','die Währung','di ve-rung'),
 'investment':('투자','tuja','die Investition','di in-ves-ti-tsion'), 'bond':('채권','chaegwon','die Anleihe','di an-lai-e'),
 'dividend':('배당금','baedanggeum','die Dividende','di di-vi-den-de'), 'loan':('대출','daechul','der Kredit','der kre-dit'),
 'debt':('빚','bit','die Schulden','di syul-den'), 'budget':('예산','yesan','das Budget','das by-dsye'),
 'insurance':('보험','boheom','die Versicherung','di fer-zi-khe-rung'), 'credit card':('신용카드','sinyongkadeu','die Kreditkarte','di kre-dit-kar-te'),
 'supply':('공급','gonggeup','das Angebot','das an-ge-bot'), 'demand':('수요','suyo','die Nachfrage','di nakh-fra-ge'),
 'inflation':('인플레이션','inpeulleisyeon','die Inflation','di in-fla-tsion'), 'wholesale':('도매','domae','der Großhandel','der gros-han-del'),
 'retail':('소매','somae','der Einzelhandel','der ain-tsel-han-del'), 'supplier':('공급업체','gonggeubeopche','der Lieferant','der li-fe-rant'),
 'brand':('브랜드','beuraendeu','die Marke','di mar-ke'), 'competition':('경쟁','gyeongjaeng','der Wettbewerb','der vet-be-verp'),
 'company':('회사','hoesa','die Firma','di fir-ma'), 'revenue':('매출','maechul','der Umsatz','der um-zats'),
 'expenses':('비용','biyong','die Ausgaben','di aus-ga-ben'), 'capital (funds)':('자본','jabon','das Kapital','das ka-pi-tal'),
 'owner':('소유주','soyuju','der Inhaber','der in-ha-ber'), 'employee':('사원','sawon','der Mitarbeiter','der mit-ar-bai-ter'),
 'sales':('판매','panmae','der Verkauf','der fer-kauf'), 'marketing':('마케팅','maketing','das Marketing','das mar-ke-ting'),
 # science
 'microscope':('현미경','hyeonmigyeong','das Mikroskop','das mi-kro-skop'), 'test tube':('시험관','siheomgwan','das Reagenzglas','das re-a-gents-glas'),
 'result':('결과','gyeolgwa','das Ergebnis','das er-gep-nis'), 'hypothesis':('가설','gaseol','die Hypothese','di hy-po-te-ze'),
 'data':('데이터','deiteo','die Daten','di da-ten'), 'observation':('관찰','gwanchal','die Beobachtung','di be-o-bakh-tung'),
 'sample':('샘플','saempeul','die Probe','di pro-be'), 'scientist':('과학자','gwahakja','der Wissenschaftler','der vi-sen-syaft-ler'),
 'atom':('원자','wonja','das Atom','das a-tom'), 'molecule':('분자','bunja','das Molekül','das mo-le-kyl'),
 'cell':('세포','sepo','die Zelle','di tse-le'), 'force':('힘','him','die Kraft','di kraft'),
 'gravity':('중력','jungnyeok','die Schwerkraft','di syver-kraft'), 'magnet':('자석','jaseok','der Magnet','der mag-net'),
 'vibration':('진동','jindong','die Schwingung','di syving-ung'), 'pressure':('압력','amnyeok','der Druck','der druk'),
 'star':('별','byeol','der Stern','der syytern'), 'moon':('달','dal','der Mond','der mont'),
 'sun':('태양','taeyang','die Sonne','di zo-ne'), 'volcano':('화산','hwasan','der Vulkan','der vul-kan'),
 'earthquake':('지진','jijin','das Erdbeben','das ert-be-ben'), 'climate':('기후','gihu','das Klima','das kli-ma'),
 'oxygen':('산소','sanso','der Sauerstoff','der zau-er-syytof'), 'fossil':('화석','hwaseok','das Fossil','das fo-sil'),
 'brain':('뇌','noe','das Gehirn','das ge-hirn'), 'heart':('심장','simjang','das Herz','das herts'),
 'blood':('피','pi','das Blut','das blut'), 'bone':('뼈','ppyeo','der Knochen','der kno-khen'),
 'virus':('바이러스','baireoseu','das Virus','das vi-rus'), 'bacteria':('세균','segyun','die Bakterien','di bak-te-ri-en'),
 'vaccine':('백신','baeksin','der Impfstoff','der impf-syytof'), 'medicine':('약','yak','das Medikament','das me-di-ka-ment'),
 # industry
 'machine':('기계','gigye','die Maschine','di ma-syi-ne'), 'turbine':('터빈','teobin','die Turbine','di tur-bi-ne'), 'motor':('모터','moteo','der Motor','der mo-tor'),
 'conveyor belt':('컨베이어 벨트','keonbeieo belteu','das Förderband','das fer-der-bant'), 'generator':('발전기','baljeongi','der Generator','der ge-ne-ra-tor'),
 'pump':('펌프','peompeu','die Pumpe','di pum-pe'), 'sensor':('센서','senseo','der Sensor','der zen-zor'),
 'control panel':('제어판','jeeopan','die Schalttafel','di syalt-ta-fel'),
 'laborer':('근로자','geulloja','der Hilfsarbeiter','der hilfs-ar-bai-ter'), 'foreman':('현장 감독','hyeonjang gamdok','der Vorarbeiter','der for-ar-bai-ter'),
 'engineer':('엔지니어','enjinieo','der Ingenieur','der in-zye-nyer'), 'technician':('기술자','gisulja','der Techniker','der tekh-ni-ker'),
 'shift':('교대 근무','gyodae geunmu','die Schicht','di syikht'), 'labor union':('노동조합','nodongjohap','die Gewerkschaft','di ge-verk-syaft'),
 'wage':('임금','imgeum','der Lohn','der lon'), 'workplace safety':('산업 안전','saneop anjeon','der Arbeitsschutz','der ar-baits-syuts'),
 'raw material':('원자재','wonjajae','der Rohstoff','der ro-syytof'), 'rubber':('고무','gomu','der Gummi','der gu-mi'),
 'coal':('석탄','seoktan','die Kohle','di ko-le'), 'textile':('섬유','seomyu','das Textil','das teks-til'),
 'packaging':('포장','pojang','die Verpackung','di fer-pa-kung'), 'warehouse':('창고','changgo','das Lager','das la-ger'),
 'shipment':('출하','chulha','die Lieferung','di li-fe-rung'), 'label':('라벨','rabel','das Etikett','das e-ti-ket'),
 'to assemble':('조립하다','joripada','montieren','mon-ti-ren'), 'to weld':('용접하다','yongjeopada','schweißen','syvai-sen'),
 'to inspect':('검사하다','geomsahada','prüfen','pry-fen'), 'to recycle':('재활용하다','jaehwaryonghada','recyceln','ri-sai-keln'),
 'waste':('폐기물','pyegimul','der Abfall','der ap-fal'), 'pollution':('오염','oyeom','die Verschmutzung','di fer-symu-tsung'),
 'automation':('자동화','jadonghwa','die Automatisierung','di au-to-ma-ti-zi-rung'), 'maintenance':('유지 보수','yuji bosu','die Wartung','di var-tung'),
}
